version: '3'

services:
  generic-organization:
    image: gitlab.etuitus.it:4567/tin/generic-organization:latest_dev
    build: .
    command: >
      bash init_system INIT
    volumes:
    - .:/code
    ports:
    - "8015:8015"
    env_file:
    - generic_organization_conf.env
    networks:
    - pool_network

  # algod:
  #   container_name: "algorand-sandbox-algod"
  #   build:
  #     context: .
  #     dockerfile: ./images/algod/Dockerfile
  #     args:
  #       CHANNEL: "stable"
  #       URL: ""
  #       BRANCH: ""
  #       SHA: ""
  #       BOOTSTRAP_URL: "<network>.algorand.network"
  #       GENESIS_FILE: "genesis/testnet/genesis.json"
  #       TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  #       ALGOD_PORT: "4001"
  #       KMD_PORT: "4002"
  #   ports:
  #     - 4001:4001
  #     - 4002:4002

  # indexer:
  #   container_name: "algorand-sandbox-indexer"
  #   build:
  #     context: .
  #     dockerfile: ./images/indexer/Dockerfile
  #     args:
  #       URL: ""
  #       BRANCH: ""
  #       SHA: ""
  #   ports:
  #     - 8980:8980
  #   restart: unless-stopped
  #   environment:
  #     DISABLED: "true"
  #     PORT: "8980"
  #     SNAPSHOT: ""
  #     CONNECTION_STRING: "host=indexer-db port=5432 user=algorand password=algorand dbname=indexer_db sslmode=disable"
  #     ALGOD_ADDR: "algod:4001"
  #     ALGOD_TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  #   depends_on:
  #     - indexer-db
  #     - algod

  # indexer-db:
  #   image: "postgres:13-alpine"
  #   container_name: "algorand-sandbox-postgres"
  #   ports:
  #     - 5433:5432
  #   environment:
  #     POSTGRES_USER: algorand
  #     POSTGRES_PASSWORD: algorand
  #     POSTGRES_DB: indexer_db
networks:
   pool_network:
