FROM ubuntu:18.04

RUN useradd -ms /bin/bash indy

# Install environment

RUN apt-get update -y && apt-get install -y \
	wget \
	python3-pip \
	python-setuptools \
	apt-transport-https \
	ca-certificates

WORKDIR /home/indy

RUN pip3 install -U \
	pip \
	setuptools

ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip3 install -r requirements.txt
COPY . /code/
RUN pip install qrcode
RUN pip install pillow
#algorand
#RUN chmod 755 /bin/*
#RUN apt-get update
#RUN apt-get install -y git
#RUN git clone https://github.com/algorand/sandbox.git
#RUN chmod -R 777 sandbox
#RUN su
#RUN apt-get install -y docker-compose
#RUN cd sandbox
#RUN apt-get install -y sudo
#RUN ./sandbox up


